-- ---------------------------------------------------------------------------
-- M2 — learning content tables (roadmap Phase 1)
--
-- Moves lesson content out of the JS bundle and into the database so it can be
-- authored, edited and later AI-generated without a redeploy. Rows are written by
-- the seeder (supabase/seed/content.sql, generated by scripts/seed-content.mjs)
-- and read by the browser, so every table here is public-read and client-immutable.
--
-- Apply with the Supabase CLI, or paste into the SQL editor: the file is idempotent
-- in the same style as schema.sql (M1). Order matters — content depends on M1 only
-- for the auth roles, not for any table.
--
-- Two choices worth stating, because they are not obvious from the DDL:
--
--  * Ids are stable text slugs derived from the topic, not uuids. topic_scores
--    already stores topic_id as text and Phase 2 joins on it, and a seeder that
--    computes an id from the content can be re-run without orphaning yesterday's
--    progress rows.
--  * `position` is 0-based and is the number the URL already carries:
--    #topic-<id>/theory-2 is the lesson at position 2. Keeping the two equal means
--    a deep link resolves to the same row whichever tree serves the content.
--
-- The (exercise_id, question_number) key is the one real invariant in here: saved
-- progress indexes answers by question num, so two questions sharing a num inside
-- one exercise would silently overwrite each other's score. Postgres owns that
-- check, and the seeder validates it too so the failure surfaces before the insert.
-- ---------------------------------------------------------------------------

create table if not exists public.topics (
  id text primary key,
  number integer not null,
  name text not null,
  english_name text,
  category text,
  description text,
  icon text,
  -- Actual ingested exercises, not the count the catalogue advertises. The two
  -- differ for the 28 topics that are declared but unauthored, and the dashboard
  -- should stop claiming 12 exercises exist when none do.
  exercise_count integer not null default 0,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

create table if not exists public.lessons (
  id text primary key,
  topic_id text not null references public.topics(id) on delete cascade,
  position integer not null,
  title text not null,
  usage_text text,
  -- Shape varies by topic ({ordinary,be,notes} for tenses, {custom,rules} for
  -- sequence-of-tenses) and the render branch keys off it, so it stays a document
  -- rather than being flattened into columns that only some topics fill.
  formula jsonb,
  signals_text text,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint lessons_topic_position_key unique (topic_id, position)
);

create table if not exists public.exercises (
  id text primary key,
  topic_id text not null references public.topics(id) on delete cascade,
  position integer not null,
  title text not null,
  description text,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint exercises_topic_position_key unique (topic_id, position)
);

create table if not exists public.exercise_questions (
  id text primary key,
  exercise_id text not null references public.exercises(id) on delete cascade,
  position integer not null,
  question_number integer not null,
  question_type text not null default 'fill',
  question_text text,
  answer text,
  explanation text,
  -- {A: "...", B: "..."} — a document because the option letters are the answer
  -- key for choice questions; a text[] would lose which letter maps to which text.
  options jsonb,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint exercise_questions_exercise_position_key unique (exercise_id, position),
  constraint exercise_questions_exercise_number_key unique (exercise_id, question_number)
);

-- ---------------------------------------------------------------------------
-- Row level security: anyone reads, nobody below service_role writes.
--
-- No insert/update/delete policy exists for these tables at all, so a client is
-- denied by RLS even if a grant is later widened by mistake. The explicit revoke
-- below is the same rule stated a second way; both are cheap and the cost of
-- getting it wrong is public content becoming vandalisable.
-- ---------------------------------------------------------------------------

alter table public.topics enable row level security;
alter table public.lessons enable row level security;
alter table public.exercises enable row level security;
alter table public.exercise_questions enable row level security;

drop policy if exists "topics_select_public" on public.topics;
create policy "topics_select_public"
  on public.topics for select
  to anon, authenticated
  using (true);

drop policy if exists "lessons_select_public" on public.lessons;
create policy "lessons_select_public"
  on public.lessons for select
  to anon, authenticated
  using (true);

drop policy if exists "exercises_select_public" on public.exercises;
create policy "exercises_select_public"
  on public.exercises for select
  to anon, authenticated
  using (true);

drop policy if exists "exercise_questions_select_public" on public.exercise_questions;
create policy "exercise_questions_select_public"
  on public.exercise_questions for select
  to anon, authenticated
  using (true);

revoke insert, update, delete, truncate, references, trigger
  on public.topics, public.lessons, public.exercises, public.exercise_questions
  from anon, authenticated;

grant select on public.topics, public.lessons, public.exercises, public.exercise_questions
  to anon, authenticated;
